name: Poetry CI

on:
  push:
    paths:
      - 'python/pyproject.toml'
      - 'python/safety-policy.yml'
      - '.github/workflows/python.yml'

jobs:
  scan:
    name: Build and test App
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install poetry
        run: pip install poetry
        working-directory: python
      - name: Build app
        run: poetry build
        working-directory: python
      - name: Test app
        run: |
          poetry install
          poetry run coverage run -m pytest
          poetry run coverage report
          poetry run coverage xml
        working-directory: python
      - name: Scan CVEs
        run: poetry export --without-hashes -f requirements.txt | poetry run safety check --full-report --stdin --policy-file safety-policy.yml
        working-directory: python